services:
    #
    # Cli Application
    #
    GrumPHP\Console\Application:
        class: Symfony\Component\Console\Application
        calls:
            - { method: 'setDispatcher', arguments: ['@Symfony\Component\EventDispatcher\EventDispatcher'] }
            - { method: 'setCommandLoader', arguments: ['@console.command_loader'] }
        configurator: ['@GrumPHP\Console\ApplicationConfigurator', 'configure']
        public: true

    GrumPHP\Console\ApplicationConfigurator:
        arguments:
            - '@config'

    #
    # Commands
    #
    GrumPHP\Console\Command\ConfigureCommand:
        arguments:
            - '@GrumPHP\Configuration\Resolver\TaskConfigResolver'
            - '@grumphp.util.filesystem'
            - '@GrumPHP\Util\Paths'
        tags:
            - { name: 'console.command' }
    GrumPHP\Console\Command\RunCommand:
        arguments:
            - '@config'
            - '@locator.registered_files'
            - '@GrumPHP\Runner\TaskRunner'
        tags:
            - { name: 'console.command' }
    GrumPHP\Console\Command\Git\CommitMsgCommand:
        arguments:
            - '@config'
            - '@locator.changed_files'
            - '@GrumPHP\Runner\TaskRunner'
            - '@grumphp.util.filesystem'
            - '@GrumPHP\Util\Paths'
        tags:
            - { name: 'console.command' }
    GrumPHP\Console\Command\Git\DeInitCommand:
        arguments:
            - '@grumphp.util.filesystem'
            - '@GrumPHP\Util\Paths'
        tags:
            - { name: 'console.command' }
    GrumPHP\Console\Command\Git\InitCommand:
        arguments:
            - '@config'
            - '@grumphp.util.filesystem'
            - '@process_builder'
            - '@GrumPHP\Util\Paths'
        tags:
            - { name: 'console.command' }
    GrumPHP\Console\Command\Git\PreCommitCommand:
        arguments:
            - '@config'
            - '@locator.changed_files'
            - '@GrumPHP\Runner\TaskRunner'
        tags:
            - { name: 'console.command' }
