services:
    formatter.raw_process:
        class: GrumPHP\Formatter\RawProcessFormatter
    formatter.php_cs_fixer:
        class: GrumPHP\Formatter\PhpCsFixerFormatter
    formatter.phpcs:
        class: GrumPHP\Formatter\PhpcsFormatter
