services:
    GrumPHP\Locator\AsciiLocator:
        arguments:
            - '@config'
            - '@filesystem'
            - '@GrumPHP\Util\Paths'
        public: true

    locator.external_command:
        class: GrumPHP\Locator\ExternalCommand
        arguments:
            - '%bin_dir%'
            - '@executable_finder'
        public: true

    locator.changed_files:
        class: GrumPHP\Locator\ChangedFiles
        arguments:
            - '@git.repository'
            - '@filesystem'
            - '@GrumPHP\Util\Paths'
        public: true

    locator.registered_files:
        class: GrumPHP\Locator\RegisteredFiles
        arguments:
            - '@git.repository'
        public: true

    GrumPHP\Locator\GitDirLocator:
        arguments:
            - '@executable_finder'
        public: false

    GrumPHP\Locator\GitHooksDirLocator:
        arguments:
            - '@filesystem'
            - '@GrumPHP\Util\Paths'
        public: true
