services:
    GrumPHP\Collection\TasksCollection: ~
    GrumPHP\Runner\TaskRunner:
        class:
        arguments:
            - '@GrumPHP\Collection\TasksCollection'
            - '@GrumPHP\Runner\MiddlewareStack'
    GrumPHP\Runner\MiddlewareStack:
        factory: ['GrumPHP\Runner\MiddlewareStack', 'fromIterable']
        arguments:
            - !tagged 'grumphp.runner_middleware'

    GrumPHP\Runner\TaskHandler\TaskHandler:
        factory: ['GrumPHP\Runner\TaskHandler\TaskHandler', 'fromIterable']
        arguments:
            - !tagged 'grumphp.task_handler'

    #
    # Runner middleware
    #
    GrumPHP\Runner\Middleware\TasksFilteringRunnerMiddleware:
        arguments: ~
        tags:
            - { name: 'grumphp.runner_middleware', priority: 1000 }
    GrumPHP\Runner\Middleware\EventDispatchingRunnerMiddleware:
        arguments:
            - '@GrumPHP\Event\Dispatcher\Bridge\SymfonyEventDispatcher'
        tags:
            - { name: 'grumphp.runner_middleware', priority: 500 }
    GrumPHP\Runner\Middleware\GroupByPriorityMiddleware:
        arguments:
            - '@grumphp.io'
        tags:
            - { name: 'grumphp.runner_middleware', priority: 200 }
    GrumPHP\Runner\Middleware\StopOnFailureRunnerMiddleware:
        arguments: ~
        tags:
            - { name: 'grumphp.runner_middleware', priority: 100 }
    GrumPHP\Runner\Middleware\HandleRunnerMiddleware:
        arguments:
            - '@grumphp.io'
            - '@GrumPHP\Runner\TaskHandler\TaskHandler'
        tags:
            - { name: 'grumphp.runner_middleware', priority: 0 }

    #
    # Task handler middleware
    #
    GrumPHP\Runner\TaskHandler\Middleware\EventDispatchingTaskHandlerMiddleware:
        arguments:
            - '@GrumPHP\Event\Dispatcher\Bridge\SymfonyEventDispatcher'
        tags:
            - { name: 'grumphp.task_handler', priority: 500 }
    GrumPHP\Runner\TaskHandler\Middleware\NonBlockingTaskHandlerMiddleware:
        arguments: ~
        tags:
            - { name: 'grumphp.task_handler', priority: 200 }
    GrumPHP\Runner\TaskHandler\Middleware\ParallelProcessingMiddleware:
        arguments:
            - '@GrumPHP\Runner\Parallel\PoolFactory'
        tags:
            - { name: 'grumphp.task_handler', priority: 100 }
    GrumPHP\Runner\TaskHandler\Middleware\ErrorHandlingTaskHandlerMiddleware:
        arguments: ~
        tags:
            - { name: 'grumphp.task_handler', priority: 0 }

    #
    # Configurable Parallel Pool
    #
    GrumPHP\Runner\Parallel\PoolFactory:
        arguments:
            - '%parallel%'
