services:
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    process_builder:
        class: Symfony\Component\Process\ProcessBuilder
        prototype: true

    git.repository:
        class: GitElephant\Repository
        arguments: [%git_dir%]

    task_runner:
        class: GrumPHP\TaskRunner

    locator.external_command:
        class: GrumPHP\Locator\ExternalCommand
        arguments: [%base_dir%, %bin_dir%, @filesystem]

    locator.changed_files:
        class: GrumPHP\Locator\ChangedFiles
        arguments: [@git.repository]
