services:
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    process_builder:
        class: Symfony\Component\Process\ProcessBuilder
        prototype: true

    task_manager:
        class: GrumPHP\TaskManager
