services:
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    process_builder:
        class: Symfony\Component\Process\ProcessBuilder
        prototype: true

    task_manager:
        class: GrumPHP\TaskManager

    locator.external_command:
        class: GrumPHP\Locator\ExternalCommand
        arguments: [%base_dir%, %bin_dir%]

    locator.changed_files:
        class: GrumPHP\Locator\ChangedFiles
        arguments: [%git_dir%]
