parameters:
  bin_dir: ./vendor/bin
  git_dir: .
  tasks: []
  extensions: []
  ascii:
    failed: grumphp-grumpy.txt
    succeeded: grumphp-happy.txt

services:
    config:
        class: GrumPHP\Configuration\GrumPHP
        arguments:
          - '@service_container'

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    executable_finder:
        class: Symfony\Component\Process\ExecutableFinder

    process_builder:
      class: GrumPHP\Process\ProcessBuilder
      arguments:
        - '@locator.external_command'

    git.repository:
        class: Gitonomy\Git\Repository
        arguments:
          - '%git_dir%'

    task_runner:
        class: GrumPHP\Runner\TaskRunner
        arguments:
          - '@event_dispatcher'

    locator.external_command:
        class: GrumPHP\Locator\ExternalCommand
        arguments:
          - '%bin_dir%'
          - '@executable_finder'

    locator.changed_files:
        class: GrumPHP\Locator\ChangedFiles
        arguments:
          - '@git.repository'

    locator.registered_files:
        class: GrumPHP\Locator\RegisteredFiles
        arguments:
          - '@git.repository'

    task.phpcs:
        class: GrumPHP\Task\Phpcs
        arguments:
          - '@config'
          - '@process_builder'
        tags:
          - {name: grumphp.task, config: phpcs}

    task.phpcsfixer:
        class: GrumPHP\Task\Phpcsfixer
        arguments:
          - '@config'
          - '@process_builder'
        tags:
          - {name: grumphp.task, config: phpcsfixer}

    task.phpspec:
        class: GrumPHP\Task\Phpspec
        arguments:
          - '@config'
          - '@process_builder'
        tags:
          - {name: grumphp.task, config: phpspec}

    task.phpunit:
        class: GrumPHP\Task\Phpunit
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: phpunit}

    task.behat:
        class: GrumPHP\Task\Behat
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: behat}

    task.git.blacklist:
        class: GrumPHP\Task\Git\Blacklist
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: git_blacklist}

    task.git.commitmessage:
        class: GrumPHP\Task\Git\CommitMessage
        arguments:
            - '@config'
        tags:
            - {name: grumphp.task, config: git_commit_message}

    task.codeception:
        class: GrumPHP\Task\Codeception
        arguments:
            - '@config'
            - '@process_builder'
        tags:
            - {name: grumphp.task, config: codeception}
