services:
  subscriber.stash_unstaged_changes:
    class: GrumPHP\Event\Subscriber\StashUnstagedChangesSubscriber
    arguments:
      - '@config'
      - '@git.repository'
    tags:
      - { name: grumphp.event_subscriber }
