services:
  subscriber.stash_unstaged_changes:
    class: GrumPHP\Event\Subscriber\StashUnstagedChangesSubscriber
    arguments:
      - '@config'
      - '@git.repository'
      - '@grumphp.io'
    tags:
      - { name: grumphp.event_subscriber }
    public: true

  GrumPHP\Event\Subscriber\VerboseLoggerSubscriber:
    arguments:
      - '@grumphp.logger'
      - '@GrumPHP\Configuration\GuessedPaths'
    tags:
      - { name: grumphp.event_subscriber }
