language: php

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
    - php: 7.0
  allow_failures:
    - php: hhvm-nightly
    - php: 7.0
  fast_finish: true

before_install:
  - composer selfupdate

install:
  - composer update --prefer-dist  --no-scripts  --no-interaction

script:
   - ./vendor/bin/phpcs --standard=PSR2 src
   - ./vendor/bin/phpspec run

