language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.3
    - php: 5.3
      env: DEPENDENCIES='low'
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: DEPENDENCIES='low'
    - php: 7.0
    - php: hhvm
  fast_finish: true

before_install:
  - composer selfupdate

install:
  - if [ "$DEPENDENCIES" != "low" ]; then travis_retry composer update --prefer-dist --no-scripts --no-interaction; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then travis_retry composer update --prefer-lowest --no-scripts --no-interaction; fi;

script:
   - ./bin/grumphp run

notifications:
  irc:
    channels:
      - "chat.freenode.net#grumphp"
